config/routes.rb
Rails.application.routes.draw do
  
  get 'password_resets/new'

  get 'password_resets/edit'

  root 'static_pages#home'
  get '/home' => 'static_pages#home', as: :home
  get '/about' => 'static_pages#about', as: :about
  get '/help' => 'static_pages#help', as: :help
  
  get '/signup' => 'users#new'
  get '/members' => 'users#index'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'

  resources :users
  resources :posts, only: [:create, :destroy]

  get '/recaps' => 'recaps#index', as: :recaps
  get '/in_depth' => 'recaps#analysis', as: :in_depth

  resources :password_resets, only: [:new, :create, :edit, :update]

end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
	<div id="error_explanation">
		<div class="alert alert-danger">
			The form contains <%= pluralize(object.errors.count, "error") %>.
		</div>
		<ul>
			<% object.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
		</ul>
	</div>
<% end %>

app/views/shared/_feed.html.erb
<% if @all_posts.any? %>
	<ol class="posts">
		<%= render @all_posts %>
	</ol>
<% end %>

app/views/shared/_footer.html.erb
<nav class="navbar navbar-default navbar-fixed-bottom">
  <div class="container">
     <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
  	  		<li><%= link_to "Home", root_path %></li>
  	  		<li><%= link_to "About", about_path %></li>
  	  		<li><%= link_to "Help", help_path %></li>
  	  		<% if logged_in? %>
  	  			<li class="dropdown">
  	  				<a href="#" class="dropdown-toggle" data-toggle="dropdown">Account <b class="caret"></b>
  	  				</a>
  	  				<ul class="dropdown-menu">
                <li><%= link_to "Recaps", recaps_path %></li>
                <li><%= link_to "In-Depth", in_depth_path %></li>
                <li><%= link_to "Users", users_path %></li>
  	  					<li><%= link_to "Profile", current_user %></li>
  	  					<li><%= link_to "Settings", edit_user_path(current_user) %></li>
  	  					<li class="divider"></li>
  	  					<li>
  	  						<%= link_to "Log out", logout_path, method: :delete %>
  	  					</li>
  	  				</ul>
  	  			</li>
  	  		<% else %>
  	  			<li><%= link_to "Log in", login_path %></li>
  	  		<% end %>
  	  	</ul>
      </div>
  </div>
</nav>

app/views/shared/_post_form.html.erb
<%= form_for(@post, html: { multipart: true }) do |f| %>
	<%= render 'shared/error_messages', object: f.object %>
	<div class="field">
		<%= f.text_area :content, placeholder: "Did you see that ludicrous display last night? ..." %>
	</div>
	<%= f.submit "Post", class: "btn btn-success" %>
	<span class="picture">
		<%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png,image/svg+xml' %>
	</span>
<% end %>	



<script type="text/javascript">
	$('#post_picture').bind('change', function() {
	    size_in_megabytes = this.files[0].size/1024/1024;
	    if (size_in_megabytes > 5) {
	      alert('Maximum file size is 5MB. Please choose a smaller file.');
	    }
	  });
</script>

app/views/shared/_signup_modal.html.erb
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal" data-whatever="@mdo">Open modal for @mdo</button>


<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="exampleModalLabel">New message</h4>
      </div>
      <div class="modal-body">
        <form>
          <div class="form-group">
            <label for="recipient-name" class="control-label">Recipient:</label>
            <input type="text" class="form-control" id="recipient-name">
          </div>
          <div class="form-group">
            <label for="message-text" class="control-label">Message:</label>
            <textarea class="form-control" id="message-text"></textarea>
          </div>
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Send message</button>
      </div>
    </div>
  </div>
</div>

app/views/shared/_user_info.html.erb
<%= link_to image_tag(current_user.image.url(:thumb), class: "post-images"), current_user %>
<h5><%= link_to current_user.firstname, current_user %></h5>